server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/products/**
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/orders/**
        - id: PaymentService
          uri: lb://PaymentService
          predicates:
            - Path=/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
