server:
  port: 9005

spring:
  application:
    name: cartservice

datasource:
  url: jdbc:mysql://localhost:3306/cartdb
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
