server:
  port: 9008

spring:
  application:
    name: notificationservice

notification:
  email:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
