server:
  port: 9006

spring:
  application:
    name: orderservice

datasource:
  url: jdbc:mysql://localhost:3306/ordersdb
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
