server:
  port: 9002

spring:
  application:
    name: userservice

datasource:
  url: jdbc:mysql://localhost:3306/usersdb
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
